# Используем официальный образ Swagger UI
FROM swaggerapi/swagger-ui


# Копируем swagger.json в контейнер
COPY ./docs/swagger.json /swagger.json

# Конфигурируем Swagger UI для использования этого файла
ENV SWAGGER_JSON=/swagger.json
