version: '3.9'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile.App
    ports:
      - "8080:8080"
    networks:
      - my-network

  swagger-ui:
    image: swaggerapi/swagger-ui # Используем официальный образ Swagger UI
    ports:
      - "8081:8080" # Swagger UI доступен на порту 8081

    volumes:
      - ./docs:/usr/share/nginx/html # Монтируем локальную папку с документом
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
